name: Terraform Security Check

on:
  workflow_run: 
    workflows: ["Terraform Validate"]
    types:
      - completed
  workflow_dispatch:
  

jobs:
  terraform:
    name: 'Security Check'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }} 
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      WORKING_DIR: ./web-demo

    steps:
      - uses: actions/checkout@master
      - name: tfsec

        uses: aquasecurity/tfsec-action@v1.0.3
        with:

          working_directory: ${{ env.Working_DIR }}
          github_token: ${{ env.GITHUB_TOKEN }}
